### ISSUE TITLE
Missing function quiz_num_participants in classes/activity.php

### ISSUE THREAD

**Issue by xuangui2018** [gjb2048/moodle-format_topcoll#101]
There is a missing function quiz_num_participants in classes/activity.php which causes the Quiz number of participants to be displayed as 0 always on course list view page.

Could you please update branch MOODLE_39 and MOODLE_310 after fixing up the issue?

Please see below the screen shot:

![image](https://user-images.githubusercontent.com/42976187/122136725-6c216700-ce86-11eb-8ee1-1cb49dc5c1dc.png)

**Comment by gjb2048** [comment]
Its not missing, just not there and 'course_participant_count' is then called as a fallback.

**Comment by gjb2048** [comment]
Ok, I can only replicate if the quiz is not available to students for any reason, like a restriction.  What is the state of yours please?

**Comment by xuangui2018** [comment]
Sorry Gareth, I have found out the problem. It was due to one the of student role's archtype was not set to 'Student' - was blank.

![image](https://user-images.githubusercontent.com/42976187/122316238-d6a5d600-cf5e-11eb-8616-0a655fcd5f44.png)
