### ISSUE TITLE
Can you please push format_topcoll version 3.9.1.5 to moodle.org?

### ISSUE THREAD

**Issue by will-bulluck** [gjb2048/moodle-format_topcoll#102]
Hey there!

Hope you're doing well, I was wondering if I could get you to push version 3.9.1.5 to moodle.org? 

Thanks,
Will

**Comment by gjb2048** [comment]
@will-bulluck Will do when I get a moment, have work to do a the moment, then plan on slowing down during Wimbledon, then at the same time, need to be sure that M3.11 version is ok, then will release M3.9 - 3.11, after that, so could be in a few weeks time.

**Comment by will-bulluck** [comment]
@gjb2048 Thanks1

**Comment by badmechanic** [comment]
OK - thank you very much for the update.



________________________________

**Comment by gjb2048** [comment]
Update, I've been working on the M3.11 version now.  Done a bit more code today and then need to sleep on it and consider if there is anything more I need to do before release.

**Comment by badmechanic** [comment]
Great!!!
Thanks for letting me know!
________________________________

**Comment by gjb2048** [comment]
Released: https://moodle.org/mod/forum/discuss.php?d=424192.

**Comment by will-bulluck** [comment]
Thanks!
