### ISSUE TITLE
Horizontal lines appeared between activities

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_topcoll#103]
There now seems to be a horizontal line between each activity/resource when using the format and no way (that I can see) to disable it. It's been commented that it's quite distracting on very busy pages. 
![Screenshot 2021-07-05 at 10 31 59](https://user-images.githubusercontent.com/664139/124450688-9460ff00-dd7c-11eb-801c-d9b9fb8a80b3.png)

**Comment by gjb2048** [comment]
@thepurpleblob What version of CT and Moodle please Howard?  As I've removed the due date from the M3.11 version.

**Comment by thepurpleblob** [comment]
It's 3.11 and the latest master (from a couple of days ago) 2021061200

So, yeh, not stable code. I just wasn't sure if it was an intentional addition or not.

**Comment by gjb2048** [comment]
Tis a core CSS thing ".section li.activity.hasinfo".

**Comment by thepurpleblob** [comment]
Ahh.... ok, appreciate the very rapid feedback.
