### ISSUE TITLE
Newer versions of Collapsed Topics plugin are not flagged for update in Moodle Notifications screen

### ISSUE THREAD

**Issue by bollycanuk** [gjb2048/moodle-format_topcoll#104]
When newer versions of plugins are available in the Moodle.org plugins library, there is generally a notice on the Site Administration/Notifications screen indicating newer versions of plugins are available. For some reason this never happens with the Collapsed Topics (format_topcoll) plugin, at least for the last 5 versions.

I am currently running Moodle 3.11+ (Build: 20210520) using the Fordson v3.10 release 2.2 theme on a Virtual Private Server.

**Comment by gjb2048** [comment]
I'm filling in all the correct information.  The M3.11 is a release candidate version and is the first release for M3.11 and will be stated as for it.  I did not state you can upgrade from a M3.11- version as that is different.  I don't know what is going on as not my code.  I always (mostly) post update messages on the course and course formats forum and my Twitter.  If you still think its an issue, then raise a Moodle site tracker issue and someone could investigate why the information I enter is either not working or correct.

**Comment by bollycanuk** [comment]
Hi Gareth,

Thanks for the reply. Much appreciated.

Derek
