### ISSUE TITLE
Support the new Student activity completion

### ISSUE THREAD

**Issue by lucaboesch** [gjb2048/moodle-format_topcoll#107]
Hi Collapsed topics format developers.

Do you plan to support the new Student activity completion displaying options (without the right hand side checkbox)?
Did you deliberate over this topic?

Best,
Luca

**Comment by gjb2048** [comment]
?  Moodle 3.11 version?  If so then I already do.  I did think about it and decided it was not the responsibility of the course format to make such a decision.

**Comment by lucaboesch** [comment]
Of course.
Sorry about my ignorant question.
I had the 3.10 course/format/topcoll in a 3.11 Moodle.
Closing.

Best,
Luca
