### ISSUE TITLE
Activity::metaused should check if the course uses topcoll before ->get_settings to avoid error.

### ISSUE THREAD

**Issue by davidscotson** [gjb2048/moodle-format_topcoll#108]
There is an observer that watches for enrolment changes so that topcoll can update it's activity metadata.

Currently, this will be called when enrolling users into courses using other course types.

If the course format doesn't have a ->get_settings() call then an error will be thrown (see screenshot).

Returning false if the course format is not set to topcoll before the line that errors seems like it would be enough to avoid this.

**Comment by davidscotson** [comment]
![Screenshot 2021-08-20 at 09 40 19](https://user-images.githubusercontent.com/7288187/130209671-8c5b11ae-0ec6-4032-8a43-9b4e9a8a0c1c.png)

**Comment by gjb2048** [comment]
@davidscotson Thanks for this David, I'd not considered that scenario and was about to release the code!

So you're actively running my development code?

**Comment by davidscotson** [comment]
Yeah, we have some internal test servers that update themselves directly from the github of various 3rd party plugins we use to make sure we're ahead of the game when incompatabilities come up with our internal stuff.

One of our QA spotted this while testing something else.

We have thought about only deploy the actual package release once things are uploaded to pluginsdb, but overall direct git fetch was simplest way to get the most recent code from a variety of sources and keep them all up to date with a script.

**Comment by gjb2048** [comment]
Oooh :)

Perhaps the best way is for the script to monitor the 'releases' (not tags) on GitHub as they, 99% of the time, result in a Moodle dot org plugin DB entry.

**Comment by gjb2048** [comment]
@davidscotson Updated, please could you test :).

**Comment by gjb2048** [comment]
So confident, I'm going for a release!

**Comment by gjb2048** [comment]
FYI: https://moodle.org/mod/forum/discuss.php?d=425903.
