### ISSUE TITLE
backport lang strings for caches

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#110]
Hi Gareth,
Just a quick note that https://github.com/gjb2048/moodle-format_topcoll/commit/874fa1e85c1ad6f606fe333beed63317a4e6ef65 could do with backporting into MOODLE_39 (and I'm guessing MOODLE_310)

Thanks!
Alistair

**Comment by gjb2048** [comment]
Dear @aspark21,

If you would please look at the commit history of my branches, then you'll see that I already do this as a matter of course and do intend to do so.

G
