### ISSUE TITLE
Collapsed topics rollover settings aren't accessible

### ISSUE THREAD

**Issue by LearnTribe** [gjb2048/moodle-format_topcoll#111]
The collapsed topics page layout has options to specify changing both the background colour of section headers, and the text of the section headers when you select or rollover the header. This is useful to clarify which section the user is interacting with. Infortunately, if the section is selected, the text remains in its original colour unless you actively point the mouse at the text.

See screenshot - section 3 is the current active selection, and section 4 is being selected while the mourse is pointing at the text.

The correct action should be to change the text colour when the background colour changes, not just when the mouse is directly pointing at the text - ie both colour changes should be triggered by rollover/selection of the section, not as separate actions.
![rollover collapsed topics](https://user-images.githubusercontent.com/3930422/134913251-0f6ce2e0-be66-4c9e-8fa3-830774b119ae.jpg).

**Comment by gjb2048** [comment]
Theme and Moodle version please.  'Infortunately'?

**Comment by gjb2048** [comment]
And what version of Collapsed Topics please?

**Comment by LearnTribe** [comment]
Unfortunately some of us occasionally enter a typo.
It's on Moodle 3.11 with the Glasgow Uni Hillhead theme, based on Boost https://github.com/lexxkoto/hillhead
Collapsed Topics - I'm not sure of the version, but the readme file for the collapsed topics states "This version works with Moodle 3.11 version 2021051700.00 (Build: 20210517) and above within the 3.11 branch until the next release."

**Comment by gjb2048** [comment]
Note to self:

.toggle span -> .toggle > span -> .toggle .the_toggle

& higher up with pseudo selector.
