### ISSUE TITLE
Collapsed topics not working with Massaction block

### ISSUE THREAD

**Issue by almadog** [gjb2048/moodle-format_topcoll#112]
Moodle 3.9.10
Collapsed topics 2020071811 (MOODLE_39 branch, commit cd442546e241b344daf47047ba975e9ef8ad19ca) 

Massaction block does not work with Collapsed topics. Course sections are not selectable.

![image](https://user-images.githubusercontent.com/114595/135110432-5b2344fc-da37-4b4f-bc2f-289ef48a1df2.png)
![image](https://user-images.githubusercontent.com/114595/135110624-a17f38d6-6f5b-48ed-aa9b-ba6f4ae6f216.png)

**Comment by gjb2048** [comment]
@almadog Collapsed Topics (CT) has a different structure to the sections in order to operate.  Therefore, this is likely to be causing the issue and also CT because of this won't be able to change, so in conclusion the 'Mass Actions' block needs to adapt to cope.
