### ISSUE TITLE
Error in urls for additional information

### ISSUE THREAD

**Issue by monnardj** [gjb2048/moodle-format_topcoll#116]
In the latest version of the plugin (3.11.0.4), the urls that allow teachers to access the grading pages for activities contain an error : ampersands are encoded in the url. Because of this, the links do not work. For instance :
`/mod/assign/view.php?action=grading&id=716558&tsort=timesubmitted&filter=require_grading`
has become :
`/mod/assign/view.php?action=grading&amp;id=716558&amp;tsort=timesubmitted&amp;filter=require_grading`

This is probably due to the introduction of the sectioncmmeta template in course_renderer.php, which replaced html_writer, and treats specials characters differently.

**Comment by gjb2048** [comment]
@monnardj Interesting, thanks for reporting.

**Comment by gjb2048** [comment]
@monnardj Please apply / make the changes in https://github.com/gjb2048/moodle-format_topcoll/commit/15de3a3c2694618aa6534ac5a1f470ff4f539ade and confirm it solves the bug.

**Comment by monnardj** [comment]
It works now for the links to the grading pages.

However, the edit section link (under cog icon) for section 0 is incorrect (still has `&amp;` inside). Line 110 in section.mustache should probably be changed similarly to line 101.

**Comment by gjb2048** [comment]
@monnardj The patch (https://github.com/gjb2048/moodle-format_topcoll/commit/15de3a3c2694618aa6534ac5a1f470ff4f539ade) already has that fix.

**Comment by monnardj** [comment]
The patch only changed line 101 in section.mustache, not line 110, which I also had to change to remove the `&amp;`.

**Comment by gjb2048** [comment]
@monnardj Thanks, I'm only human! -> new patch https://github.com/gjb2048/moodle-format_topcoll/commit/10e5080af6d46e6a19856582a60981e21ba34e10.

**Comment by monnardj** [comment]
Everything working fine, now ! And thanks for your great plugins 👍
