### ISSUE TITLE
Results for lesson activity (mdl 3.9)

### ISSUE THREAD

**Issue by klasuk** [gjb2048/moodle-format_topcoll#117]
Meta for activity lesson seems to have changed for release version of moodle 3.9
https://github.com/gjb2048/moodle-format_topcoll/blob/MOODLE_39/classes/activity.php#L365

Function std_meta cannot get correct parameters $submissiontable and $keyfield
and onward function get_submission_row is failing here: https://github.com/gjb2048/moodle-format_topcoll/blob/MOODLE_39/classes/activity.php#L709

How to fix this?

**Comment by gjb2048** [comment]
https://moodle.org/mod/forum/discuss.php?d=429093#p1728005
