### ISSUE TITLE
Topics not expanding

### ISSUE THREAD

**Issue by vanboosh** [gjb2048/moodle-format_topcoll#119]
When you click on a topic, they wont expand, but 'open all' and 'close all' still works.

We're using version 3.1.1.3 on Moodle version 3.1.1

**Comment by gjb2048** [comment]
Dear @vanboosh,

That is a very old version and I'm only running M3.9+ at the moment locally, so will need to be paid if you'd like my support on this one.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
@vanboosh No reply in nearly a year, closing.
