### ISSUE TITLE
Indentation not working in moodle 4.0

### ISSUE THREAD

**Issue by PhMemmel** [gjb2048/moodle-format_topcoll#120]
In moodle 4.0 the format declares to support indentation and apparently, it does seem to support it.

However, there is no visible effect when an activity is being indented (tested on plain moodle 4.0 master)

**Comment by gjb2048** [comment]
@PhMemmel Thanks for the report, fixed in the associated patch.

**Comment by PhMemmel** [comment]
Can confirm it works. Thank you for the super quick response and fix!
