### ISSUE TITLE
Hidden sections are not distinguished enough

### ISSUE THREAD

**Issue by lucaboesch** [gjb2048/moodle-format_topcoll#127]
There is no enough indication that a section is hidden.
That is not accessible.

**To Reproduce**
1. Create a course
2. Choose collapsed topic format
3. Toggle foreground 000 Toggle background FFF
4. Turn on editing, hide a section

**Expected behaviour**
Hidden and shown sections can be distinguished. In our font we have no italics, so there is no clue, also merely changing the colour of the titles of the hidden sections wouldn't be enough.

**Screenshots**
<img width="859" alt="image" src="https://user-images.githubusercontent.com/377279/203160899-3ffc03c7-a65c-4c35-8cc9-8b3b1c9fed6b.png">

** Version (please complete the following information) **
- Collapsed Topics 400.1.2
- Moodle 4.0.5

**Comment by gjb2048** [comment]
Dear Luca,

And what do you think of the core solution:

![Screenshot 2022-11-21 221918](https://user-images.githubusercontent.com/1058419/203169672-20b03f9d-b417-4c1d-8fce-557598c62584.png)

as I've seen mixed reviews?

Please supply concrete evidence with research to justify your assertion of "There is no enough indication that a section is hidden. That is not accessible.", as currently this reads as one person's opinion.  There needs to be more science to this to provide a foundation for fully understanding that any given potential solution will solve the possible problem.

Regards,

Gareth

**Comment by gjb2048** [comment]
P.S. In the mean time, please change to using an italic supporting font.

**Comment by gjb2048** [comment]
Dear @lucaboesch,

Ok, you've raised the issue, flamed at me with angry words "There is no enough indication that a section is hidden. That is not accessible.".  I've asked for more information and now you've not even come back!

Please reply soon or I'll just implement what I think and leave it at that.  My current progress being with the badges.

Gareth

**Comment by lucaboesch** [comment]
Dear Gareth
Please allow me to humbly apologize, I wasn't trying to be flaming in no way!
My silence here was partly in hope to have maybe other readers express themselves with thoughts, too (I'm not an accessibility expert).
In fact, I find the approach with the same pill as Boost core does very useful and in fact I've even been trying to implement it, but was not successful.
So, let me express my gratitude to you 1) taking this feedback seriously and 2) doing something about it!
Best,
Luca

**Comment by gjb2048** [comment]
Dear @lucaboesch,

Thank you for your reply and explanation.  Often the best place if you want input from others is the Course and Course formats forum -> https://moodle.org/mod/forum/view.php?id=47.  I'm a moderator of the forum so tend to check it several times a day, seven days a week.

Ok, in the 'master' branch, this is what I've been able to achieve so far:

![Screenshot 2022-11-25 121909](https://user-images.githubusercontent.com/1058419/203985256-026a71d7-7eba-4d6a-8f5c-4188c6640cf6.png)
![Screenshot 2022-11-25 121950](https://user-images.githubusercontent.com/1058419/203985261-cbfbb73a-930a-4e00-9625-c6ab478937ce.png)

so that the badges show even when the section is collapsed and regardless of editing state.

Kind regards,

Gareth

**Comment by lucaboesch** [comment]
This is excellent stuff, @gjb2048 also on behalf of my lecturer who's noticed this I have to convey many thanks to you, Gareth.

**Comment by gjb2048** [comment]
Dear @lucaboesch 

Thank you for letting me know and your kind words.  Does the solution solve the problem fully for you?  And so can be closed after I check if its needed for M3.11?

And, I've just released the M4.1 version with it incorporated -> https://moodle.org/mod/forum/discuss.php?d=441011

Kind regards,

Gareth

**Comment by lucaboesch** [comment]
Brilliant.
Yes, you can close @gjb2048.
Best,
Luca
