### ISSUE TITLE
4.2dev - fatal error

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#128]
Moodle: master (4.2dev)
topcoll: master @ [0c738d6](https://github.com/gjb2048/moodle-format_topcoll/commit/0c738d61a55425dc5074392b0c28d89c2745305d)

PHP Fatal error:  Cannot override final method core_courseformat\base::get_context() in /home/runner/work/moodle-gha-demo/moodle-gha-demo/course/format/topcoll/lib.php on line 1693

Run PHPUnit test setup and this occurs

**Comment by ralf-krause** [comment]
The course format 'topcoll' can't be used with the released Moodle 4.2 (20230424).

**Comment by gjb2048** [comment]
Yes it can!  If you look at the master branch, I've already started on a M4.2 version!

**Comment by ralf-krause** [comment]
Great!

**Comment by consuelogarcue** [comment]
Topcoll doesn't work on Moodle 4.2+ (Build: 20230427)

**Comment by gjb2048** [comment]
@consuelogarcue Yes it does in the 'master' development branch.

**Comment by consuelogarcue** [comment]
Do we have to download the version from GitHub?
The one that is downloaded from Moodle.org crashes the system

**Comment by gjb2048** [comment]
@consuelogarcue Yes.  That is the current 'development' version and I've not finished developing it yet.  And the one on Moodle dot org is for M4.1 'ONLY' as stated all over the place and does not 'crash' Moodle 4.1.

**Comment by gjb2048** [comment]
Fixed -> https://moodle.org/plugins/format_topcoll/402.1.0/29153
