### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by gdkraus** [gjb2048/moodle-format_topcoll#13]
Have you ever considered making the tool more accessible to users with disabilities? As it is now it's fairly good, but there are some improvements that need to be made for screen reader users - for instance, notifying users the status of whether or not a section is collapsed. You can do this with ARIA techniques. It would look something like Example 1 at the following.

http://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions

I'm happy to work with you on this.

**Comment by gjb2048** [comment]
I've worked for accessibly on Grid and applied ARIA there.  With Collapsed Topics it used to always be expanded for screen readers when that setting was there.  I've not had time to take things further or more critically input from users on the specific changes needed.

If you have patches in the form of pull requests on the master branch, then I'll happily consider them thank you.

**Comment by gjb2048** [comment]
Hi gdkraus,

Do you have anything for me?

Cheers,

Gareth

**Comment by gjb2048** [comment]
Any information please?

**Comment by swatki** [comment]
Hi, I'm not sure if gdkraus is still monitoring this issue... in a previous position at NCSU (ncsu.edu) he was highly involved with accessibility and Moodle, but he left this position in July, 2015.

**Comment by gjb2048** [comment]
@swatki Thanks, things moved on now, closing.
