### ISSUE TITLE
Deleting sections doesn't work in some layouts

### ISSUE THREAD

**Issue by olivabigyo** [gjb2048/moodle-format_topcoll#130]
**Describe the bug**
Deleting sections is broken in layouts without section numbers.

**To Reproduce**
Steps to reproduce the behaviour:
1. In the 'Collapsed Topics' plugin setting change 'Layout' to anything without section numbers, eg. 'No additions'. (Can do it in a course settings.)
2. Edit a course with 'Collapsed Topics' format.
3. (optional) Add a new section at the bottom
4. Click the 3 dots next to a section, click 'Delete section'
5. The sections below the deleted one are renumbered, but the deleted section is not removed. There is also an error message in the JS console. (The section is actually removed from the DB and will not be present after a reload.)

**Expected behaviour**
The section disappears after deletion.

**Screenshots**

**Version (please complete the following information)**
- Collapsed Topics version: 400.1.2
- Moodle version: 4.0.6

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - not tested

**Additional context**

**Comment by gjb2048** [comment]
@olivabigyo Thanks for this, I'll see of I can replicate as soon as I can.  Given my comments on #131 - then why does the Topics format not suffer from the same issue?

**Comment by olivabigyo** [comment]
I have replied in the PR. Crucially, your code has an additional part that's different from the Topics format (to update the section numbers), which is where the bug is triggered.

The core Moodle might or might not have a similar issue (which is harder to trigger), this requires more investigation. Definitely the documentation of the `getElement` method is incorrect.

**Comment by gjb2048** [comment]
@olivabigyo Thanks, saw that just after I posted my reply and have replied there.

**Comment by gjb2048** [comment]
@olivabigyo Also, would you like a credit in the Changes.md file?

**Comment by olivabigyo** [comment]
Thank you for the quick handling!
Credit: why not, thanks :)

**Comment by gjb2048** [comment]
@olivabigyo No problem.  Credit added and patch forward ported to master, currently for M4.1.
