### ISSUE TITLE
Move Left/Move Right doesn't work till page refresh

### ISSUE THREAD

**Issue by jwalits** [gjb2048/moodle-format_topcoll#136]
Move Left/Move right doesn't work till page refresh

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any course using the Collapsed Topics format
2. Turn editing mode on
3. On any activity, click on the 3 dots and click "Move Right" or "Move Left"
4. The section remains as is. Once you refresh the page, section will be indented.

**Expected behaviour**
When "Move Right" or "Move left" is clicked, the section should be indented without needing page to be manually refreshed

**Versions**
 - Moodle: 4.1.4+ (Build: 20230728)
 - Format: 401.1.1
 - Browser and version: Chrome version 115.0.5790.102, Firefox version 116.0

**Comment by gjb2048** [comment]
@jwalits CT currently does not react to this event and the area is difficult to understand.  It's on my TODO list.

**Comment by gjb2048** [comment]
cm_moveleft etc.

![Screenshot 2023-08-01 165243](https://github.com/gjb2048/moodle-format_topcoll/assets/1058419/aef7b649-12cb-4df5-8b3b-ea273d1923b2)

**Comment by jwalits** [comment]
Hey @gjb2048 - thanks for the quick feedback and the patch. We will test it out and let you know shortly if everything is working as expected.

Thanks again.

**Comment by gjb2048** [comment]
@jwalits Any news on your testing please?

**Comment by jwalits** [comment]
Hey @gjb2048, sorry for the late update. This patch is working well - we're seeing the sections update correctly without having to refresh the page.

Thanks again for getting the patch out quickly. Much appreciated.

**Comment by gjb2048** [comment]
Dear @jwalits, thanks for letting me know.

**Comment by jwalits** [comment]
Marking this issue as resolved. Thanks again for the quick action @gjb2048
