### ISSUE TITLE
Indentation not working

### ISSUE THREAD

**Issue by PhMemmel** [gjb2048/moodle-format_topcoll#143]
**Describe the bug**
In the activity's dropdown menu you can select "Move right" and sometimes(!?) "Move left", but nothing happens to the activity card. format_topcoll should either declare to not support this feature (so the option to move right/left will not be shown) or implement it correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a course
2. Add some activities
3. In edit mode click on the three-dots beside an activity and click "Move right"
4. See that the activity card will not move at all.

**Expected behaviour**
Indentation should work correctly like for example in format_topics

**Versions (please complete the following information):**
 - Moodle: tested on current master and moodle 4.2 stable branch
 - Format: latest master
 - Browser: same on all browsers I tested (Chrome mobile, Chrome Win Desktop)

**Comment by gjb2048** [comment]
@PhMemmel Are you sure you have the latest 'master'?  As:

- https://github.com/gjb2048/moodle-format_topcoll/issues/136
- https://moodle.org/mod/forum/discuss.php?d=449412

**Comment by PhMemmel** [comment]
Thank you very much for the fast response.

You are right. I had double checked if I used the latest master before reporting, but something apparently was still outdated. I fixed that and indentation works. Very sorry for the noise!
