### ISSUE TITLE
Cannot Edit

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#15]
Moodle 2.7 STABLE - latest release
Plugin Version 2.7.3
The Edit dropdown menu does not appear for the activities / resources across all themes when the course  uses the topcoll format. This broke somewhere between version 2.7.1.5 and 2.7.3

**Comment by gjb2048** [comment]
I'm working on it and about to put out a fix: https://moodle.org/mod/forum/discuss.php?d=278977#p1199117

**Comment by gjb2048** [comment]
Broke in 2.7.3.

**Comment by aspark21** [comment]
Thanks Gareth!

**Comment by gjb2048** [comment]
Fixed:

M2.7: https://moodle.org/plugins/pluginversion.php?id=7819
M2.8: https://moodle.org/plugins/pluginversion.php?id=7820
