### ISSUE TITLE
Managers assigned at Course Category levels cannot change topcoll settings until course exists

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_topcoll#24]
To reproduce

- Create a course category and assign a user (with no site assignments) the Manager role at that category
- log in as that user
- create a new course within the category, give it a name and shortname and change the course format to "Collapsable topics' 
- The page automatically refreshes but the collapsable topics settings are not shown (the issue!)
- save the course settings page (creating the course) and work your way back to the settings page
- the topcoll settings are now all shown

Analysis:
When a course is in the process of being created (on the settings page for the first time) and the course doesn't exist yet, the courseid defaults to 1 in the class format_topcoll, i.e. the 'front page' course. This is set in the class constructor. These users are assigned the Manager role in subcategories not the site itself. So, at this stage they do not have the 'changelayout' capability (because they have no site rights). Only when the settings page is saved and the course is created do they acquire these rights and can see the settings. 

I think the fix is to make the context in which capabilities are checked become that of the parent category if no course currently exists.

**Comment by gjb2048** [comment]
Thanks Howard, twitchy nose says that this is a core issue as I'm using the capabilities API as documented.

**Comment by thepurpleblob** [comment]
Yes - but I think the issue is that you're asking, "what's the context for this course to check the capability against?",  "there isn't one, so we'll arbitrarily choose $COURSE->id". This could probably be almost anything I suppose but was '1' for me as I had started from the front page. Anyway, I'm not sure it's clear cut but my feeling is that as you create a course within a Course Category that should be the context to check the capability against while the new course is still being created.

**Comment by gjb2048** [comment]
Hi Howard,

Please could you test the 'master' branch (Moodle 3.0) or apply the commit https://github.com/gjb2048/moodle-format_topcoll/commit/947db89214689bc33347d2385110a5f1599c73e9 to your test version and see if it fixes it for you along with not breaking anything as far as you can tell.

Cheers,

Gareth

**Comment by thepurpleblob** [comment]
Yep - that fixes it for Moodle 3.0. Thanks very much. 

I'm still running 2.9 for the next few months. Do you think the patch would cherry-pick into the 2.9 version?

**Comment by gjb2048** [comment]
Hi Howard,

Yes.  I've worked hard to keep the CT functionality the same as far back as M2.7 version.  Thanks for testing.

Gareth

**Comment by gjb2048** [comment]
Hi Howard,

Now released: https://moodle.org/mod/forum/discuss.php?d=329248

Cheers,

Gareth
