### ISSUE TITLE
Deprecated constructor in js/tc_colourpopup.php

### ISSUE THREAD

**Issue by roperto** [gjb2048/moodle-format_topcoll#26]
Deprecated constructor in:

https://github.com/gjb2048/moodle-format_topcoll/blob/master/js/tc_colourpopup.php#L42

**Comment by gjb2048** [comment]
Depreciated in what version of PHP please?

**Comment by tbannister** [comment]
[Deprecated as of PHP 7.0](http://php.net/manual/en/language.oop5.decon.php), support to be removed in a future version of PHP.

**Comment by gjb2048** [comment]
Integrated in: https://github.com/gjb2048/moodle-format_topcoll/pull/27.
