### ISSUE TITLE
Moodle 3.2 compatibility - convert format_topcoll_delete_course to observer of event \core\event\course_content_deleted

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#28]
Moodle: 3.2 latest Stable
topcoll: latest master 

Debugging: Callback delete_course is deprecated. Function format_topcoll_delete_course should be converted to observer of event \core\event\course_content_deleted
https://travis-ci.org/aspark21/moodle/jobs/189218110#L1714

**Comment by gjb2048** [comment]
Ah ok,  only a depreciation notice.  Not urgent.

**Comment by gjb2048** [comment]
Addressed in: https://github.com/gjb2048/moodle-format_topcoll/commit/28197b9088661e0d3549e81f26be3a2c98373504.
