### ISSUE TITLE
in edit mode, the color of the section name is not set

### ISSUE THREAD

**Issue by actXc** [gjb2048/moodle-format_topcoll#29]
I use essential and moodle 3.2.2
When switching to edit mode, the section name color is not set correctly.
I guess because it becomes an "a" tag while in editmode to have a button etc.
It needs an additional css tag to set the color also in edit mode- but I cant find a solution.   
Try with 
text color: #ffffff background-color : #000000
hover text color: #000000 background-color: #ffffff

**Comment by gjb2048** [comment]
Hi Guido,

Tested in M3.3 version and cannot replicate.

G

**Comment by gjb2048** [comment]
Hi Guido,

Tested in M3.2 with Essential and cannot replicate.  Working as expected.

G
