### ISSUE TITLE
Option to display topics in multiple columns uses old Boostrap classes

### ISSUE THREAD

**Issue by lexxkoto** [gjb2048/moodle-format_topcoll#33]
The option to display topics in multiple columns uses the old Bootstrap 2 column classes (i.e. "row-fluid", "span3", "span4" and "span6". This doesn't work in newer versions of Boostrap (used by the Boost theme).

These should be replaced with the newer Boostrap "col-[xs|sm|md|lg|xl]-*" class names.

**Comment by gjb2048** [comment]
You're wrong, not broken in Boost see: https://github.com/gjb2048/moodle-format_topcoll/blob/master/renderer.php#L1126.

**Comment by gjb2048** [comment]
And: https://github.com/gjb2048/moodle-format_topcoll/blob/master/renderer.php#L1118
