### ISSUE TITLE
Additional sections created when migrated from 2.5.4 to 3.4

### ISSUE THREAD

**Issue by karikalankumaresan** [gjb2048/moodle-format_topcoll#38]
I have migrated Moodle from 2.5.4 to 3.4.1 (ofcourse in stages). I have downloaded the Collapsed Topic format (ver: 2017110300) from the moodle plugin directory for 3.4. I use subpage activity under every section. While it has migrated all the content fine, it has the following issues,

1. All the sections have been migrated fine (along with the subpages, which has scorm packages / files in it), however there are additional sections created (Section 110, Section 114 etc) which contains the items under the subpages (from initial sections). 

2. Hiding those sections hides the section, but also the packages/files under the section and it is not visible from the subpage in initial sections as well. 

3. Removing those sections removes the section, but also the packages/files under the section.

4. Also, migrated course does not have the limit to specify for topics in the course settings, while the new course has that option.

I cannot re-add those packages/files since those have some statistics associated with it. So, it is a kind of blocker and I am not able to proceed further. It seems to be a bug, any help would be greatly appreciated.

**Comment by gjb2048** [comment]
What course format were you using at M2.5.4?

**Comment by gjb2048** [comment]
Also please post annotated screen shots so I can understand the problem, if any to do with CT.

**Comment by karikalankumaresan** [comment]
@gjb2048 I have used Collapsed Topic course format in 2.5.4. The attached is the screenshot which explains the problem. ie, Before upgradation "Modulo 4: la Gestion de la Actividad" section contains "Clase" and "Bibiloteca" subpages and under that we have scorm packages. After upgradation, "Modulo 4: la Gestion de la Actividad" is upgraded fine but there is a new section "Section 10" was created automatically and the content of the subpages are listed directly in that section (as you see in the screenshot attached). Like this many courses are impacted due to upgradation. Hiding/Removing the section "Section 10" hides/removes the content as well, which is an issue.

![section](https://user-images.githubusercontent.com/24779190/37886622-11b63e82-30da-11e8-9ae0-4ee770f8a733.png)

**Comment by gjb2048** [comment]
Were the scorm activities originally in a orphaned section?

**Comment by karikalankumaresan** [comment]
Yes, they were.

**Comment by gjb2048** [comment]
Ok, then, this is functionality change in Moodle core, please read the documentation.
