### ISSUE TITLE
Re-implement Number of sections setting for Moodle 3.3 / 3.4 +

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#39]
In Moodle 3.3, stealth activities were implemented but in doing so stealth / orphaned activities were also done away with. There is a tracker item to bring these back (https://tracker.moodle.org/browse/MDL-59481) but in the meantime all orphaned sections are being displayed and that tracker wouldn't fix things until 3.6 at the earliest. 

It particularly affects us as we used subpages (https://github.com/moodleou/moodle-mod_subpage) so have now over 100 orphaned sections being displayed which shouldn't.

In Moodle 3.2 and prior the topcoll course format had a "Number of sections" setting. Re-implementing this as a filter of the maximum number of topics to display for that course would seem to be the most straightforward way of resolving our current situation.

**Comment by gjb2048** [comment]
Hi @aspark21,

Perhaps it would.  Currently the format is in line with core in this respect and does not require extra effort on my part to cope with any difference.  Would you be willing to fund my time to do this please?

Gareth

**Comment by aspark21** [comment]
Hi Gareth,

Seeing how critical this is going to be to us for our upgrade to Moodle 3.4 I would hope that we could find some funding for this - sent you a message to that effect via your about.me site.

Thanks
Alistair

**Comment by gjb2048** [comment]
Hi Alistair,

That doesn't seem to be working, please contact me via my Moodle profile.

Gareth

**Comment by aspark21** [comment]
Fixed in V3.4.0.3 and V3.5.01

**Comment by ProfRobin** [comment]
Please let me know how this can be implemented in Moodle 3.4.3.  I miss the ability to select the number of sections!  Any help is appreciated.

**Comment by gjb2048** [comment]
Do you mean Moodle core?

**Comment by ProfRobin** [comment]
Probably... I am not a tech person, so I am not sure of all of the
language.

In 3.2, we could select the number of sections to display in each course
individually.  In 3.4.3, we cannot.  The thread here seems to show that
many others want that feature back in Moodle.  I was told on Moodle
Communities that you were working on a fix.

thanks
*Robin Owens Latham*
Professor & Master Instructor, English & Fundamental Studies Dept.
Advisor, Phi Theta Kappa - Beta Upsilon Delta Chapter
Faculty Liaison for Turnitin
Nash Community College
Rocky Mount NC
*"Let us always meet each other with a smile, **for the smile is the
beginning of love." *
*- Mother Teresa *


*Email correspondence to and from this address may be subject to the North
Carolina Public Records Law and may be disclosed to third parties by an
authorized state official. (NCGS.Ch.132)*

**Comment by gjb2048** [comment]
Ok, they told you incorrect information.  I have implemented the setting back in Collapsed Topics, but that is a contributed course format. I am not working on a patch for Moodle core itself.  You've also stated 'here' with no link.  If you want the functionality back in core itself then please read: https://docs.moodle.org/dev/Tracker_introduction - there might be an issue already for it.

**Comment by ProfRobin** [comment]
Hey
Thanks.
I'm already in that tracker thread as well. I'll keep following it.
Thanks for responding.
R

**Comment by jimjudges** [comment]
@gjb2048 Hi Gareth please can you confirm which version of your Collapsed Topics plugin gives access to numsections in course settings?
Many thanks for any help - Jim

**Comment by gjb2048** [comment]
Hi Jim,

The ones with 'numsections' in the lib.php file.

G

**Comment by aspark21** [comment]
@jimjudges see https://github.com/gjb2048/moodle-format_topcoll/issues/39#issuecomment-407351842 any versions higher than these has this fix

**Comment by bfriesenvcc** [comment]
I think I may have discovered an interesting little (minor) side-effect of bringing back the number of sections.

We just upgraded from Moodle 3.4 to 3.6 and have received more and more reports of missing sections. With editing turned on, we can see they aren't actually missing, but they are Orphaned. Simply increasing the number of sections corrects the issue. No problem.

My theory (and it's just a theory) is that the "orphaned" sections were added during the period that the numsections variable was not in use and when numsections was reinstated it started using whatever contents was there before and didn't include any new sections.

Example: Moodle 3.2 course had 5 sections. During Moodle 3.4 period, instructor added 3 sections, but there was no update to the numsections field, since it was no longer being used. After Moodle 3.6 upgrade, course had 5 visible sections (from the old numsections field) and 3 orphaned sections. Adding the 3 extra sections "un-orphaned" the previously orphaned sections and updated the numsections field.

Gareth, do you think this is what happened, or am I totally out to lunch?

**Comment by gjb2048** [comment]
No because of the logic of this code in 'course_format_options' in 'lib.php':

```
            if ($courseid == 1) { // New course.
                 $defaultnumsections = $courseconfig->numsections;
            } else { // Existing course that may not have 'numsections' - see get_last_section().
                global $DB;
                $defaultnumsections = $DB->get_field_sql('SELECT max(section) from {course_sections}
                    WHERE course = ?', array($courseid));
            }
            $courseformatoptions = array(
                'numsections' => array(
                    'default' => $defaultnumsections,
                    'type' => PARAM_INT,
                ),
```

**Comment by gjb2048** [comment]
Unless, 'numsections' was already in the database and indeed was not updated then the default would not be applied and the old value would be true.  Humm, you could be correct.

**Comment by bfriesenvcc** [comment]
Darn. I thought I'd solved a mystery. :-(

**Comment by gjb2048** [comment]
Snag is now I don't know how to solve this.

**Comment by bfriesenvcc** [comment]
I appreciate you considering it. Maybe it's related to our upgrade process? Those steps are taken care of by our more technical guys in I.T. I only work with things accessible through the Moodle U.I.

**Comment by gjb2048** [comment]
Not related to the upgrade process 'ish' but more that I don't think there is a 'numsections' removal from the database removal code at the time that it went.  Otherwise I would / may have copied it and perhaps not in the mess now.
