### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by syn** [gjb2048/moodle-format_topcoll#40]
When using the latest topcoll master,  an upgrade is performed normally, 
However doing a second upgrade for something unrelated fails due to a version mismatch in the topcol plugin.

Default exception handler: Cannot downgrade format_topcoll from 2017111301 to 2017110301. Debug: 
Error code: cannotdowngrade
* line 656 of /lib/upgradelib.php: downgrade_exception thrown
* line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
* line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Cannot downgrade format_topcoll from 2017111301 to 2017110301. !!!
!! 
Error code: cannotdowngrade !!
!! Stack trace: * line 656 of /lib/upgradelib.php: downgrade_exception thrown
* line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
* line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!

**Comment by gjb2048** [comment]
What version of Moodle are you using?

**Comment by gjb2048** [comment]
Where did you get a version file with 2017111301 as the version number?

**Comment by gjb2048** [comment]
Ok I see it in the upgrade save point.  Ok, only the 'releases' should be installed https://github.com/gjb2048/moodle-format_topcoll/releases and anything in the branches is to be considered 'development', so will rather fix the upgrade save point instead.

**Comment by gjb2048** [comment]
Ref: https://github.com/gjb2048/moodle-format_topcoll/commit/0b62691073a6e187e3dddd1e78c8dc38102d35d6#diff-c74097fbb0a2db56a0a98aaf7d6a2654R175
