### ISSUE TITLE
Return of 'numberofsections' breaks courses with >10 sections

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_topcoll#43]
Courses that had more than 10 sections in the pre-numberofsections versions of topcoll suddenly now have only 10 sections along with lots of support calls, "lots of my content has vanished". It's still there, of course, but now in orphaned sections.

**Comment by gjb2048** [comment]
Hi Howard,

Probably this: https://tracker.moodle.org/browse/CONTRIB-7393 - I've been meaning to release the patch: https://github.com/gjb2048/moodle-format_topcoll/commit/2e011f33cf8dbfa48d80a827e6798e88115abecb - but work and life has been getting in the way.

If you patch the code and as long as the course settings have not been 'saved' then things should return.

Gareth

**Comment by gjb2048** [comment]
FYI: https://moodle.org/mod/forum/discuss.php?d=374021

**Comment by thepurpleblob** [comment]
Ok, thanks. I've patched this on our sites and we'll see how we get on. 

I was a bit confused when the numberofsections option returned. I thought that was a thing of the past!

**Comment by gjb2048** [comment]
It is, but it was requested to be put back.

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-format_topcoll/commit/2e011f33cf8dbfa48d80a827e6798e88115abecb
