### ISSUE TITLE
Steps on format_weeks' get_section_dates, breaks core's analytics

### ISSUE THREAD

**Issue by OdyX** [gjb2048/moodle-format_topcoll#53]
See https://tracker.moodle.org/browse/MDL-65067 where the mere presence of format_topcoll can break core's analytics tasks, because it will try to use format_topcoll's get_section_dates wrongly.

**Comment by gjb2048** [comment]
Fair enough.

**Comment by gjb2048** [comment]
Also related https://tracker.moodle.org/browse/MDL-60702.

**Comment by gjb2048** [comment]
Note:

Waiting on https://tracker.moodle.org/browse/MDL-60702.

**Comment by gjb2048** [comment]
Fixed by #65.
