### ISSUE TITLE
Accessible back to main course link.

### ISSUE THREAD

**Issue by stuartlamour** [gjb2048/moodle-format_topcoll#66]
Hi Gareth,

as discussed screen reader users do not find the select menu useful to return to main course view.

Adding this code :

`// When viewing a section page, add a link back to the course.
            if ($section->section == 0 && $onsectionpage) {
                $o .= '<a href="' .new moodle_url('/course/view.php', array('id' => $course->id)). '"><span class="fa fa-caret-up"></span> ' .get_string('maincoursepage', 'format_topcoll'). '</a>';
            }`

to renderer.php line 523 helps with this.

If the link is only for screen reader users you could add the class sr-only and remove the icon.

Best wishes
Stuart

**Comment by gjb2048** [comment]
Had a look, might need more thought with placement, even if has 'sr-only':

![Annotation 2019-11-16 120517](https://user-images.githubusercontent.com/1058419/68992891-72de9700-0869-11ea-840b-8bf094cec1a0.jpg)

**Comment by gjb2048** [comment]
Done in M3.9+ versions.
