### ISSUE TITLE
More accessible open all / close all

### ISSUE THREAD

**Issue by stuartlamour** [gjb2048/moodle-format_topcoll#67]
Hi Gareth,

as discussed UCL report that open all/ close all buttons do not provide enough info as to what the screen reader user is opening/closing. 

Once way to approach this would be to add the string 'Sections' for screen readers.

e.g. $string['topcollopened'] = 'Open all <span class="sr-only">sections</span>';

Alternatively you could add this in at the renderer.php - line 1158ish

`$o .= html_writer::tag('span', get_string('topcollopened', 'format_topcoll').'  '.get_string('sections'),
            array('class' => 'on ' . $this->tctoggleiconsize, 'id' => 'toggles-all-opened',
            'role' => 'button', 'tabindex' => '0')
        );`

**Comment by gjb2048** [comment]
My gut stays to add more information to the button (role is button) using the title attribute: https://www.w3schools.com/tags/att_global_title.asp.
