### ISSUE TITLE
Crosshair and Edit link overwritten by long activity title

### ISSUE THREAD

**Issue by haietza** [gjb2048/moodle-format_topcoll#68]
When an activity has a long title, the crosshair to the left (with editing turned on) and the Edit link to the right are overwritten by the activity title.

We are using version 3.6.0.3 2018121902 of the plugin and 3.6.5 of Moodle.

<img width="423" alt="Screen Shot 2019-11-10 at 10 42 33 AM" src="https://user-images.githubusercontent.com/669666/68546710-4af1be00-03a7-11ea-94c3-f9082da726b4.png">

**Comment by gjb2048** [comment]
Cannot replicate on version 3.6.1.0 (current) with the Boost theme.  Please update and see if the issue happens again.

**Comment by haietza** [comment]
@gjb2048 The updated version resolves the issue. Thanks so much for the quick follow up!
