### ISSUE TITLE
Auto expand highlighted sections and auto collapse non highlighted sections

### ISSUE THREAD

**Issue by Syxton** [gjb2048/moodle-format_topcoll#69]

**Comment by gjb2048** [comment]
Bug? Enhancement?

**Comment by Syxton** [comment]
@gjb2048 Is it supposed to work that way?  If it is then Bug.  If it isn't designed to work that way, then Enhancement.

**Comment by gjb2048** [comment]
Uh?

**Comment by Syxton** [comment]
ok, let's go with Enhancement.

**Comment by gjb2048** [comment]
You've just logically contradicted yourself.  If it already works that way then you're saying its a bug and therefore should not.  If it does not work that way then you're saying it should and therefore is an enhancement, which means that when implemented then by your logic its a bug and needs to be removed.

**Comment by Syxton** [comment]
Ok, let me be clear. It does NOT currently work this way.  I don't know if it was designed to work this way but has a bug, or if it wasn't designed to work this way and I am requesting an enhancement.

**Comment by gjb2048** [comment]
Ok then could you provide more details please, along with contact details of the person (if not you) who has financial authority to approve work and I would then be able to quote costs and take things from there.

**Comment by gjb2048** [comment]
Currently the selected section / current is open and the others are closed (if that's the default) for page load.

**Comment by gjb2048** [comment]
@Syxton Umm... ok that was a tad abrupt!  I'll take it you don't wish me to implement the enhancement?
