### ISSUE TITLE
Long previous and next topic titles overwrite current topic title

### ISSUE THREAD

**Issue by haietza** [gjb2048/moodle-format_topcoll#71]
When topics have long titles, the pagination links for the previous and next topics overwrite the current topic title and the Jump to menu when on the specific topic view (i.e. clicking the Topic # link to the right of the collapsed topic title). See attached screen shot. Thank you!
![image](https://user-images.githubusercontent.com/669666/83554233-74586f80-a4da-11ea-88fe-3a42cb24dccd.png)

**Comment by gjb2048** [comment]
Make the topics have shorter titles then!

**Comment by gjb2048** [comment]
Example stated is not an example of a real world situation that would justify the expenditure of time to solve a problem that is only conceptual through the use of test data that does not represent what would happen in the real world, even a boundary test case.

**Comment by haietza** [comment]
@gjb2048 I did not want to upload a screen shot of actual course content where the problem first presented itself, but I could share that with you privately via email if you need evidence for the justification.

**Comment by haietza** [comment]
@gjb2048 I've uploaded the actual screen shot from the course now.

**Comment by gjb2048** [comment]
As the first resource is a page called 'Module 6 Overview' where the description of such is the issue text, thus being a secondary element in the description, therefore just call the section 'Module 6' and reduce the repetition of exaggerated explanatory text.

**Comment by gjb2048** [comment]
Not a bug / issue.
