### ISSUE TITLE
New Feature: Duplicate Section 

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_topcoll#72]
One of our users really likes the duplicate section functionality available in the OneTopic Course format and was asking about having this in the Collapsed Topics course format. This creates a copy of the section including copies of all the activities in that section.

Had a quick glance and this seems to be how it's implemented - https://github.com/davidherney/moodle-format_onetopic/blob/master/duplicate.php

**Comment by gjb2048** [comment]
Fair enough @aspark21.  Would you like to fund its addition please?

**Comment by gjb2048** [comment]
Implemented in M3.9.

**Comment by mhughes2k** [comment]
Don't suppose there's any chance of a back port of this to 3.8?

**Comment by gjb2048** [comment]
@mhughes2k If you pay me for my time, then yes.
