### ISSUE TITLE
The plugin should honor MDL-68330 change

### ISSUE THREAD

**Issue by golenkovm** [gjb2048/moodle-format_topcoll#74]
These lines should have `mod-indent-outer w-100` class:

https://github.com/gjb2048/moodle-format_topcoll/blob/db00bdffc07209889dedcdc208ca0ae04a3f81d0/tests/courseformatrenderer_test.php#L284
https://github.com/gjb2048/moodle-format_topcoll/blob/db00bdffc07209889dedcdc208ca0ae04a3f81d0/tests/courseformatrenderer_test.php#L331
https://github.com/gjb2048/moodle-format_topcoll/blob/db00bdffc07209889dedcdc208ca0ae04a3f81d0/tests/courseformatrenderer_test.php#L378
https://github.com/gjb2048/moodle-format_topcoll/blob/db00bdffc07209889dedcdc208ca0ae04a3f81d0/classes/course_renderer.php#L176

**Comment by gjb2048** [comment]
Additional to #74, if 'mod-indent-outer' has 'width: 100%' added to it in the CSS then none of the PHP, including the unit tests need to change!  Simpler.

**Comment by gjb2048** [comment]
Note M3.9+ thing.

**Comment by gjb2048** [comment]
Patched with much simpler https://github.com/gjb2048/moodle-format_topcoll/commit/1b2b13fbec2ac1640a1a07764f5dd013d761220f.
