### ISSUE TITLE
Moving sections takes a very long time; >5minutes

### ISSUE THREAD

**Issue by bollycanuk** [gjb2048/moodle-format_topcoll#76]
I really like this course format, it solved a scroll of death issue we had with a 32 topic course. However we've found that if we need to move a section in Edit mode, it takes forever (10 minutes)  for the busy cursor to disappear. It doesn't seem to matter whether the moved section has a lot or no content; the time is about the same.

As a workaround we change the course format back to the generic Topics format, move things around and then change back to your Collapsed Topics format.

Thanks for all your help.
Derek

**Comment by gjb2048** [comment]
@bollycanuk Please provide:

Moodle version, CT version, screen shots / screen cast demonstrating issue.

**Comment by bollycanuk** [comment]
- Moodle 3.9.1+ (Build: 20200807)
- Collapsed Topics  3.8.1.0 (2019111701)
- Screenshot attached

Screencast to come later when no users are on the system.

![image](https://user-images.githubusercontent.com/9040146/90819254-bd5fd900-e2fd-11ea-8d69-e9a5bef8843f.png)

**Comment by gjb2048** [comment]
Why are you using the M3.8 version of CT on M3.9?

**Comment by gjb2048** [comment]
Please install 3.9.0.4 -> https://moodle.org/plugins/pluginversions.php?plugin=format_topcoll

**Comment by gjb2048** [comment]
@bollycanuk Did it work?

**Comment by bollycanuk** [comment]
Yes perfectly. Thank you.
