### ISSUE TITLE
Lesson meta information shows "Not attempted" even if it has been

### ISSUE THREAD

**Issue by mhughes2k** [gjb2048/moodle-format_topcoll#79]
If a quiz is set to unlimited attempts:
![image](https://user-images.githubusercontent.com/694841/94259176-efc8ab80-ff25-11ea-9837-ba2d77cdfcf0.png)

The Course format appears to display
![image](https://user-images.githubusercontent.com/694841/94259133-e0e1f900-ff25-11ea-8a2d-f5bedc887d2c.png)

In this case the student has completed the quiz twice and both attempts are in the "finished" state.

**Comment by gjb2048** [comment]
??? The quiz states that it was attempted on the 22 September 2020 with 'Feedback available' in the screenshot.  The highlighted area with '! Not attempted' is a 'Lesson'!!

Please confirm that the student has completed the lesson and there is an issue to actually fix.

**Comment by mhughes2k** [comment]
Oh sorry, I've been looking at so many support queries I'm going cross eyed. I'll go double check and get back to you!

**Comment by mhughes2k** [comment]
The student has done the lesson 4 times, completed it twice and not completed twice:
![image](https://user-images.githubusercontent.com/694841/94274597-c6b41500-ff3d-11ea-9058-f5b2608da19d.png)

So its not quite accurate to say that they haven't attempted it.

**Comment by gjb2048** [comment]
Ok, can replicate - no data in attempts table but is in branch and timer table.  Code from other party, don't know how to solve yet.

**Comment by gjb2048** [comment]
````
    protected static function lesson_meta(cm_info $modinst) {
        $meta = self::std_meta($modinst, 'available', 'deadline', 'lessonid', 'timer', 'lessontime', 'attempted', true);
        // TO BE DELETED: $meta->submissionnotrequired = true; ..........
        return $meta;
    }
````

````
    protected static function lesson_num_submissions($courseid, $mod) {
        return self::std_num_submissions($courseid, $mod, 'lesson', 'lessonid', 'lesson_timer');
    }
````

**Comment by gjb2048** [comment]
To done after other activity update.
