### ISSUE TITLE
Make engagement information optional

### ISSUE THREAD

**Issue by NinaHerrmann** [gjb2048/moodle-format_topcoll#80]
Hello everyone, 
from our lecturer we got the feedback, that they would like to hide the engagement information such as 'Due to' and 'submitted by x' since they have very large courses with large sections (which might not be recommendable, but it is hard to convince other people to change habits...). Anyway if you think that feature has the potential  to be integrated I would provide a pull request. 
Cheers, 
Nina

**Comment by gjb2048** [comment]
Thanks @NinaHerrmann - please supply the pull request and I'll consider it.

**Comment by NinaHerrmann** [comment]
One other thing, do you mind adding the label hacktoberfest-accepted to the pull request as part of the Hacktoberfest challenge? https://hacktoberfest.digitalocean.com/hacktoberfest-update?

**Comment by gjb2048** [comment]
So that's all I need to do?  i.e. add 'hacktoberfest-accepted' to the PR?

**Comment by gjb2048** [comment]
Done, so hopefully what is required.

**Comment by NinaHerrmann** [comment]
Yes, thank you! Also thank you for your fast feedback! :slightly_smiling_face:

**Comment by gjb2048** [comment]
Note: Current related pull https://github.com/gjb2048/moodle-format_topcoll/pull/91.

**Comment by gjb2048** [comment]
Ok, looks like 'showadditionalmoddata' is both a site and course level setting and yet its not defined in 'settings.php'!  Need to fix this.
