### ISSUE TITLE
Due date label doesn't honor overridden dates for mod_assign

### ISSUE THREAD

**Issue by golenkovm** [gjb2048/moodle-format_topcoll#82]
When the due date is overridden for a user (it might be user override or group override) the original due date is still displayed on the course page:

![image](https://user-images.githubusercontent.com/22066290/96673812-122dd780-13b3-11eb-9573-c2f787116c81.png)

**Comment by gjb2048** [comment]
@golenkovm Interesting, will look as soon as I can.

**Comment by gjb2048** [comment]
@golenkovm Merged and accepted, thank you.

**Comment by golenkovm** [comment]
Thanks @gjb2048 !
