### ISSUE TITLE
Course page is broken when a new user navigates to a course

### ISSUE THREAD

**Issue by golenkovm** [gjb2048/moodle-format_topcoll#84]
It happens only once.
How to replicate:
* Cretae a course
* Create a user
* Enrol the user to the course
* Login as user
* Navigate to the course page

![image](https://user-images.githubusercontent.com/22066290/97152724-6d056b80-17c5-11eb-8bca-0c82fcca2267.png)

**Comment by gjb2048** [comment]
Thanks @golenkovm I've been meaning to update activity from Adaptable with other changes too!  Will look at this as soon as I can.

**Comment by golenkovm** [comment]
Thank you @gjb2048
