### ISSUE TITLE
Issue with Assignment Meta-information

### ISSUE THREAD

**Issue by mhughes2k** [gjb2048/moodle-format_topcoll#86]
We have found an issue with the accuracy of the assignment meta information.

A student submitted to an assignment, subsequently restrict access conditions were set on the assignment, which meant she does not have access now. 

![image](https://user-images.githubusercontent.com/694841/97164110-8ed90100-1779-11eb-8d25-e6a7dbf5da0b.png)

The assignment is displayed if the conditions are not met, as opposed to being completely hidden.

The meta-information displayed for this is: ![image](https://user-images.githubusercontent.com/694841/97164382-f1ca9800-1779-11eb-92a5-b6b52f59bebd.png)
(this appears directly under the 1st image, but there was personally identifiable information in the Restrict Access set that I had to remove).

Which is not strictly accurate, whilst the student may no longer be subject to having to submit, they *have* submitted, and regardless of this, if they can see the activity but are not eligible to submit, the submissions status is irrelevant and shouldn't be displayed.

I believe the initial cause *is* an oversight on the RA conditions, but nevertheless under these legitimate conditions (Student submitted, student now cannot submit due to Restrict Access Conditions) that have been set up, I think the meta-information is wrong.

There doesn't appear to be any evaluation of how restrict access conditions could impact the activity meta information.

**Comment by gjb2048** [comment]
The code is pending an improvement in this from elsewhere.  However if the student cannot access the assignment and they should then that is not a fault of the course format.

**Comment by mhughes2k** [comment]
I agree, the problem is exacerbated by Moodle allowing the choice between completely obscuring the activity or having it visible but not available to them. In the first the issue is irrelevant.

It's only in this second case where the information being put in by the course format becomes an issue as it does contradict the actual status.

**Comment by gjb2048** [comment]
I'm sure I've looked at this before and 'Not submitted' is a true reflection of the status of the assignment.  And even if they can no longer submit the assignment then the status tells them what did happen.  Thus the scenario of the ability to submit passing and the student asking themselves 'Did I actually submit before the deadline' can be answered and if they haven't then they can contact a human to sort out the issue.  Therefore removing the status is not a clear cut 100% decision as there are scenarios where the information would be useful.

**Comment by gjb2048** [comment]
And given "A student submitted to an assignment, subsequently restrict access conditions were set on the assignment, which meant she does not have access now." then that is a change to the assignment after it has opened.  Therefore complex and not something for the code to 'guess' the circumstances = dangerous.

**Comment by mhughes2k** [comment]
Yes I agree a guess is dangerous, but in that vein "not submitted" is also a guess, so a preferable response would be to not output anything, no? 

After all they have submitted, the assignment itself reports it as submitted (to staff), the student knows they submitted, but the meta-information response is "not submitted" which contradicts.

**Comment by gjb2048** [comment]
Its not a guess as its based upon data within the assign table.

**Comment by gjb2048** [comment]
But things have improved so on your test system, patch with https://github.com/gjb2048/moodle-format_topcoll/blob/master/classes/activity.php and see if that makes a difference.

**Comment by gjb2048** [comment]
@mhughes2k What version are you using please?

**Comment by gjb2048** [comment]
Going with new state of 'expired' -> https://github.com/gjb2048/moodle-format_topcoll/commit/1d282deb2e5d06859216d21ef2bdfe0b6bc776dc.

Improved icons too for 'reopened' as the student has already submitted but is getting another chance.

**Comment by gjb2048** [comment]
Considering closed.
