### ISSUE TITLE
Problem with quiz badges

### ISSUE THREAD

**Issue by savva312** [gjb2048/moodle-format_topcoll#90]
Hello, our students reporting that the badge that appears below the quiz says that they didnt attempt the quiz.

This is wrong because if I check attempts the student attempted the quiz and finished it.

Is there a way to fix this or disable the badges all together?

Thank you.

![image](https://user-images.githubusercontent.com/25815376/101735805-192bb900-3acb-11eb-9372-327423094475.png)

**Comment by gjb2048** [comment]
@savva312 Please read https://github.com/gjb2048/moodle-format_topcoll/blob/master/Readme.md#reporting-issues and supply all information asked for.

**Comment by savva312** [comment]
Hello gjb2048 Thanks for the reply, here are the info

Moodle Version
$version  = 2020061501.06;
$release  = '3.9.1+ (Build: 20200807)';
$branch   = '39';  

Plugin Version
$plugin->version = 2020071804;

The theme we are using is a child theme of Boost, where we just update the colors to match our branding

Please let me know if you need any additional information.

Thank you

**Comment by gjb2048** [comment]
@savva312 Please update to version 3.9.1.0 as this has fixes in this area -> https://moodle.org/plugins/pluginversion.php?id=22819

**Comment by savva312** [comment]
Great! Ghank you for the quick reply and sorry for bothering you. I missed that 👍
