### ISSUE TITLE
Slow page load with collapsible topics

### ISSUE THREAD

**Issue by rcmantis** [gjb2048/moodle-format_topcoll#92]
A combination of the collapsible topics format and the group restrictions slow down the page load time.

**Steps to repeat:**
Add group restrictions to a course with multiple sections and the collapsible topics format. Does the page load time increase significantly?

**Comment by gjb2048** [comment]
Ok:

- What version of Moodle?
- What version of CT?
- Does this happen in the core Topics format?

**Comment by gjb2048** [comment]
And have you got the correct plugin as this is 'Collapsed Topics' -> https://moodle.org/plugins/pluginversions.php?plugin=format_topcoll -> not 'Collapsible Topics' -> https://moodle.org/plugins/format_collapsibletopics - so screen shot too please.

**Comment by gjb2048** [comment]
Screen shots too please!

**Comment by rcmantis** [comment]
- Apologies for the spelling error there. I should have spelt the course format as Collapsed Topics.

![image](https://user-images.githubusercontent.com/77673303/105045576-f7293d00-5a5f-11eb-90be-8b64ac6f441f.png)

- Moodle version: 3.9.2
- CT version 3.9.1.0
- The course with group restrictions and topics format takes ~20s, with no group restrictions and collapsible topics format takes ~20s
With both group restrictions and collapsible topics format, the load time is about 2.5 minutes.

**Comment by gjb2048** [comment]
Is CT's admin setting 'coursesectionactivityfurtherinformationassign' etc. set to 'Yes' i.e. that and the others?  If so when 'No', does that make a difference?  And could you upload an example MBZ course backup file with no users that shows this please?  i.e. one that has come from a test server.

**Comment by gjb2048** [comment]
And what sort of Group restrictions?  Visible groups? etc.  And how many users on the course?

**Comment by gjb2048** [comment]
How many assignments etc?

**Comment by rcmantis** [comment]
- Group restrictions - A course section is 'Not available (hidden) unless any of:' - criteria is to be a member of at least 1 out of 6 groupings
- Course is set to Separate groups
- there are about 190 assignments
- course has 2021 enrolled users

**Comment by gjb2048** [comment]
2021 users!!!!!  And 190 assignments!!!!  The latter has to be some sort of 'who designed this!!!' event!  Surely that has to be impossible to manage!

Ok, what about if you turn 'coursesectionactivityfurtherinformationassign' etc. off?

**Comment by gjb2048** [comment]
In any event a '20' second page load on the Topics format is not exactly 'user friendly' is it?  Is there anybody who knows what they are doing from an eLearning / Educational point of view in terms of structure and design of online courses?

**Comment by gjb2048** [comment]
Sometimes the technology is not the solution, the human is -> Garbage In Garbage Out.

**Comment by gjb2048** [comment]
@rcmantis Please respond or I'll close the issue.

**Comment by rcmantis** [comment]
Sorry for delay, yes setting all of these to 'No' reduces load time to 1.2 secs.
![image](https://user-images.githubusercontent.com/77673303/105703152-b8ceca80-5f04-11eb-9eed-82e636b03342.png)

**Comment by jmerrill86** [comment]
Hi there. 

We're actually seeing the same behavior as well with user_info_field restrictions on activities in a course. Specifically our case triggers when Show quiz information is set to true. The plugin appears to be iterating through every user enrolled in the course to check against quiz access. Please see the included XHProf info. 

![image](https://user-images.githubusercontent.com/13425077/109229514-6b5aad00-7791-11eb-994f-85bfa3715ae3.png)

**Comment by gjb2048** [comment]
Thanks for the info.  I know this is not looking good, but how else could the code determine how many users can do the quiz?  Additional: I did not write this code, but seem to have spent hour after hour fixing it.  If it doesn't work for you then please do turn it off.

**Comment by gjb2048** [comment]
@rcmantis Does turning it off solve the issue for you?

**Comment by rcmantis** [comment]
Sorry, yes I think our client has found a way to work with course format now. Thank you

**Comment by gjb2048** [comment]
@rcmantis Thank you for getting back to me.
