### ISSUE TITLE
Deprecation warning for 3.11

### ISSUE THREAD

**Issue by haietza** [gjb2048/moodle-format_topcoll#99]
We see this warning with the course format installed on Moodle 3.11:

course_section_cm_completion is deprecated and is being replaced by the activity_information output component.

    line 446 of /course/renderer.php: call to debugging()
    line 211 of /course/format/topcoll/classes/course_renderer.php: call to core_course_renderer->course_section_cm_completion()
    line 841 of /course/renderer.php: call to format_topcoll_course_renderer->course_section_cm()
    line 1056 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
    line 890 of /course/format/topcoll/renderer.php: call to core_course_renderer->course_section_cm_list()
    line 218 of /course/format/topcoll/format.php: call to format_topcoll_renderer->print_multiple_section_page()
    line 278 of /course/view.php: call to require()

**Comment by gjb2048** [comment]
Fair enough.  Note though that CT has not been made ready for Moodle 3.11 yet.

**Comment by haietza** [comment]
@gjb2048 I figured it was a bit early :), but wanted to mention it in case it helps in the prep for 3.11. Thanks a bunch!

**Comment by ndunand** [comment]
@gjb2048 first and foremost thanks for sharing this great work of yours.

Just to confirm reproducibility, we have the same issue on our Moodle 3.11.

Also, any estimated timeframe for the M3.11-ready version of this plugin?

**Comment by gjb2048** [comment]
@ndunand Timeframe = when I get it done :)

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-format_topcoll/commit/ddc6f62bf77335473c99593480df374b45ae3e6f addresses this issue, however there is now duplication of functionality with the activity meta stuff.  Need to think!  Perhaps see what happens to Adaptable.
